# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

capitals_with_country = [
    %w(	Afghanistan 	Kabul	),
    %w(	Albania 	Tirana	),
    %w(	Algeria 	Algiers	),
    %w(	Andorra 	Andorra\ la\ Vella	),
    %w(	Angola 	Luanda	),
    %w(	Antigua\ and\ Barbuda 	Saint\ John's	),
    %w(	Argentina 	Buenos\ Aires	),
    %w(	Armenia 	Yerevan	),
    %w(	Australia 	Canberra	),
    %w(	Austria 	Vienna	),
    %w(	Azerbaijan 	Baku	),
    %w(	The\ Bahamas 	Nassau	),
    %w(	Bahrain 	Manama	),
    %w(	Bangladesh 	Dhaka	),
    %w(	Barbados 	Bridgetown	),
    %w(	Belarus 	Minsk	),
    %w(	Belgium 	Brussels	),
    %w(	Belize 	Belmopan	),
    %w(	Benin 	Porto\ Novo	),
    %w(	Bhutan 	Thimphu	),
    %w(	Bolivia 	La\ Paz	),
    %w(	Bolivia 	Sucre	),
    %w(	Bosnia\ and\ Herzegovina 	Sarajevo	),
    %w(	Botswana 	Gaborone	),
    %w(	Brazil 	Brasilia	),
    %w(	Brunei 	Bandar\ Seri\ Begawan	),
    %w(	Bulgaria 	Sofia	),
    %w(	Burkina\ Faso 	Ouagadougou	),
    %w(	Burundi 	Bujumbura	),
    %w(	Cambodia 	Phnom\ Penh	),
    %w(	Cameroon 	Yaounde	),
    %w(	Canada 	Ottawa	),
    %w(	Cape\ Verde 	Praia	),
    %w(	Central\ African\ Republic 	Bangui	),
    %w(	Chad 	N'Djamena	),
    %w(	Chile 	Santiago	),
    %w(	China 	Beijing	),
    %w(	Colombia 	Bogota	),
    %w(	Comoros 	Moroni	),
    %w(	Costa\ Rica 	San\ Jose	),
    %w(	Cote\ d'Ivoire 	Yamoussoukro	),
    %w(	Cote\ d'Ivoire 	Abidjan	),
    %w(	Croatia 	Zagreb	),
    %w(	Cuba 	Havana	),
    %w(	Cyprus 	Nicosia	),
    %w(	Czech\ Republic 	Prague	),
    %w(	Democratic\ Republic\ of\ the\ Congo 	Kinshasa	),
    %w(	Denmark 	Copenhagen	),
    %w(	Djibouti 	Djibouti	),
    %w(	Dominica 	Roseau	),
    %w(	Dominican\ Republic 	Santo\ Domingo	),
    %w(	East\ Timor 	Dili	),
    %w(	Ecuador 	Quito	),
    %w(	Egypt 	Cairo	),
    %w(	El\ Salvador 	San\ Salvador	),
    %w(	Equatorial\ Guinea 	Malabo	),
    %w(	Eritrea 	Asmara	),
    %w(	Estonia 	Tallinn	),
    %w(	Ethiopia 	Addis\ Ababa	),
    %w(	Federated\ States\ of\ Micronesia 	Palikir	),
    %w(	Fiji 	Suva	),
    %w(	Finland 	Helsinki	),
    %w(	France 	Paris	),
    %w(	Gabon 	Libreville	),
    %w(	The\ Gambia 	Banjul	),
    %w(	Georgia 	Tbilisi	),
    %w(	Germany 	Berlin	),
    %w(	Ghana 	Accra	),
    %w(	Greece 	Athens	),
    %w(	Grenada 	Saint\ George's	),
    %w(	Guatemala 	Guatemala\ City	),
    %w(	Guinea 	Conakry	),
    %w(	Guinea-Bissau	Bissau	),
    %w(	Guyana 	Georgetown	),
    %w(	Haiti 	Port-au-Prince	),
    %w(	Honduras 	Tegucigalpa	),
    %w(	Hungary 	Budapest	),
    %w(	Iceland 	Reykjavik	),
    %w(	India 	New\ Delhi	),
    %w(	Indonesia 	Jakarta	),
    %w(	Iran 	Tehran	),
    %w(	Iraq 	Baghdad	),
    %w(	Ireland 	Dublin	),
    %w(	Israel 	Jerusalem	),
    %w(	Italy 	Rome	),
    %w(	Jamaica 	Kingston	),
    %w(	Japan 	Tokyo	),
    %w(	Jordan 	Amman	),
    %w(	Kazakhstan 	Astana	),
    %w(	Kenya 	Nairobi	),
    %w(	Kiribati 	Tarawa	),
    %w(	Kosovo 	Pristina	),
    %w(	Kuwait 	Kuwait\ City	),
    %w(	Kyrgyzstan 	Bishkek	),
    %w(	Laos 	Vientiane	),
    %w(	Latvia 	Riga	),
    %w(	Lebanon 	Beirut	),
    %w(	Lesotho 	Maseru	),
    %w(	Liberia 	Monrovia	),
    %w(	Libya 	Tripoli	),
    %w(	Liechtenstein 	Vaduz	),
    %w(	Lithuania 	Vilnius	),
    %w(	Luxembourg 	Luxembourg	),
    %w(	Macedonia 	Skopje	),
    %w(	Madagascar 	Antananarivo	),
    %w(	Malawi 	Lilongwe	),
    %w(	Malaysia 	Kuala\ Lumpur	),
    %w(	Maldives 	Male	),
    %w(	Mali 	Bamako	),
    %w(	Malta 	Valletta	),
    %w(	Marshall\ Islands 	Majuro	),
    %w(	Mauritania 	Nouakchott	),
    %w(	Mauritius 	Port\ Louis	),
    %w(	Mexico 	Mexico\ City	),
    %w(	Moldova 	Chisinau	),
    %w(	Monaco 	Monaco	),
    %w(	Mongolia 	Ulaanbaatar	),
    %w(	Montenegro 	Podgorica	),
    %w(	Morocco 	Rabat	),
    %w(	Mozambique 	Maputo	),
    %w(	Myanmar 	Rangoon	),
    %w(	Myanmar 	Naypyidaw	),
    %w(	Namibia 	Windhoek	),
    %w(	Nauru 	Yaren	),
    %w(	Nepal 	Kathmandu	),
    %w(	Netherlands 	Amsterdam	),
    %w(	Netherlands 	The\ Hague	),
    %w(	New\ Zealand 	Wellington	),
    %w(	Nicaragua 	Managua	),
    %w(	Niger 	Niamey	),
    %w(	Nigeria 	Abuja	),
    %w(	North\ Korea 	Pyongyang	),
    %w(	Norway 	Oslo	),
    %w(	Oman 	Muscat	),
    %w(	Pakistan 	Islamabad	),
    %w(	Palau 	Melekeok	),
    %w(	Panama 	Panama\ City	),
    %w(	Papua\ New\ Guinea 	Port\ Moresby	),
    %w(	Paraguay 	Asuncion	),
    %w(	Peru 	Lima	),
    %w(	Philippines 	Manila	),
    %w(	Poland 	Warsaw	),
    %w(	Portugal 	Lisbon	),
    %w(	Qatar 	Doha	),
    %w(	Republic\ of\ the\ Congo 	Brazzaville	),
    %w(	Romania 	Bucharest	),
    %w(	Russia 	Moscow	),
    %w(	Rwanda 	Kigali	),
    %w(	Saint\ Kitts\ and\ Nevis 	Basseterre	),
    %w(	Saint\ Lucia 	Castries	),
    %w(	Saint\ Vincent\ and\ the\ Grenadines 	Kingstown	),
    %w(	Samoa 	Apia	),
    %w(	San\ Marino 	San\ Marino	),
    %w(	Sao\ Tome\ and\ Principe 	Sao\ Tome	),
    %w(	Saudi\ Arabia 	Riyadh	),
    %w(	Senegal 	Dakar	),
    %w(	Serbia 	Belgrade	),
    %w(	Seychelles 	Victoria	),
    %w(	Sierra\ Leone 	Freetown	),
    %w(	Singapore 	Singapore	),
    %w(	Slovakia 	Bratislava	),
    %w(	Slovenia 	Ljubljana	),
    %w(	Solomon\ Islands 	Honiara	),
    %w(	Somalia 	Mogadishu	),
    %w(	South\ Africa 	Pretoria	),
    %w(	South\ Africa 	Cape\ Town	),
    %w(	South\ Africa 	Bloemfontein	),
    %w(	South\ Korea 	Seoul	),
    %w(	South\ Sudan 	Juba	),
    %w(	South\ Sudan 	Ramciel	),
    %w(	Spain 	Madrid	),
    %w(	Sri\ Lanka 	Colombo	),
    %w(	Sri\ Lanka 	Sri\ Jayewardenepura\ Kotte	),
    %w(	Sudan 	Khartoum	),
    %w(	Suriname 	Paramaribo	),
    %w(	Swaziland 	Mbabane	),
    %w(	Sweden 	Stockholm	),
    %w(	Switzerland 	Bern	),
    %w(	Syria 	Damascus	),
    %w(	Taiwan 	Taipei	),
    %w(	Tajikistan 	Dushanbe	),
    %w(	Tanzania 	Dar\ es\ Salaam	),
    %w(	Tanzania 	Dodoma	),
    %w(	Thailand 	Bangkok	),
    %w(	Togo 	Lome	),
    %w(	Tonga 	Nuku'alofa	),
    %w(	Trinidad\ and\ Tobago 	Port-of-Spain	),
    %w(	Tunisia 	Tunis	),
    %w(	Turkey 	Ankara	),
    %w(	Turkmenistan 	Ashgabat	),
    %w(	Tuvalu 	Funafuti	),
    %w(	Uganda 	Kampala	),
    %w(	Ukraine 	Kiev	),
    %w(	United\ Arab\ Emirates 	Abu\ Dhabi	),
    %w(	United\ Kingdom 	London	),
    %w(	United\ States\ of\ America 	Washington\ D.C.	),
    %w(	Uruguay 	Montevideo	),
    %w(	Uzbekistan 	Tashkent	),
    %w(	Vanuatu 	Port-Vila	),
    %w(	Vatican\ City 	Vatican\ City	),
    %w(	Venezuela 	Caracas	),
    %w(	Vietnam 	Hanoi	),
    %w(	Yemen 	Sanaa	),
    %w(	Zambia 	Lusaka	),
    %w(	Zimbabwe 	Harare	)
]

capitals_with_country.each do |c|
  country = Country.find_or_create_by!(name: c[0])
  Capital.find_or_create_by!(name: c[1], country: country)
end

states = [
    %w(	Alabama	Montgomery AL	),
    %w(	Alaska	Juneau	AK),
    %w(	Arizona	Phoenix	AZ),
    %w(	Arkansas	Little\ Rock AR	),
    %w(	California	Sacramento CA	),
    %w(	Colorado	Denver CO	),
    %w(	Connecticut	Hartford CT	),
    %w(	Delaware	Dover DE	),
    %w(	Florida	Tallahassee FL	),
    %w(	Georgia	Atlanta GA	),
    %w(	Hawaii	Honolulu HI	),
    %w(	Idaho	Boise ID	),
    %w(	Illinois	Springfield IL	),
    %w(	Indiana	Indianapolis IN	),
    %w(	Iowa	Des\ Moines IA	),
    %w(	Kansas	Topeka KS	),
    %w(	Kentucky	Frankfort KY	),
    %w(	Louisiana	Baton\ Rouge LA	),
    %w(	Maine	Augusta ME	),
    %w(	Maryland	Annapolis MD	),
    %w(	Massachusetts	Boston MA	),
    %w(	Michigan	Lansing MI	),
    %w(	Minnesota	St.\ Paul MN	),
    %w(	Mississippi	Jackson MS	),
    %w(	Missouri	Jefferson\ City MO	),
    %w(	Montana	Helena MT	),
    %w(	Nebraska	Lincoln NE	),
    %w(	Nevada	Carson\ City NV	),
    %w(	New\ Hampshire	Concord NH	),
    %w(	New\ Jersey	Trenton NJ	),
    %w(	New\ Mexico	Santa\ Fe NM	),
    %w(	New\ York	Albany NY	),
    %w(	North\ Carolina	Raleigh NC	),
    %w(	North\ Dakota	Bismarck ND	),
    %w(	Ohio	Columbus OH	),
    %w(	Oklahoma	Oklahoma\ City OK	),
    %w(	Oregon	Salem OR	),
    %w(	Pennsylvania	Harrisburg PA	),
    %w(	Rhode\ Island	Providence RI	),
    %w(	South\ Carolina	Columbia SC	),
    %w(	South\ Dakota	Pierre SD	),
    %w(	Tennessee	Nashville TN	),
    %w(	Texas	Austin TX	),
    %w(	Utah	Salt\ Lake\ City UT	),
    %w(	Vermont	Montpelier VT	),
    %w(	Virginia	Richmond VA	),
    %w(	Washington	Olympia WA	),
    %w(	West\ Virginia	Charleston WV	),
    %w(	Wisconsin	Madison WI	),
    %w(	Wyoming	Cheyenne WY	),
    %W(	Washington,\ DC #{''} DC	)
]

states.each do |s|
  State.find_or_create_by!(name: s[0], capital: s[1], abbreviation: s[2])
end

presidents = [
    %w(	George	Washington		),
    %w(	John	Adams		),
    %w(	Thomas	Jefferson		),
    %w(	James	Madison		),
    %w(	James	Monroe		),
    %w(	John	Adams	Quincy	),
    %w(	Andrew	Jackson		),
    %w(	Martin	Van\ Buren		),
    %w(	William	Harrison	Henry	),
    %w(	John	Tyler		),
    %w(	James	Polk	K.	),
    %w(	Zachary	Taylor		),
    %w(	Millard	Fillmore		),
    %w(	Franklin	Pierce		),
    %w(	James	Buchanan		),
    %w(	Abraham	Lincoln		),
    %w(	Andrew	Johnson		),
    %w(	Ulysses	Grant	S.	),
    %w(	Rutherford	Hayes	B.	),
    %w(	James	Garfield	A.	),
    %w(	Chester	Arthur		),
    %w(	Grover	Cleveland		),
    %w(	Benjamin	Harrison		),
    %w(	Grover	Cleveland		),
    %w(	William	McKinley		),
    %w(	Theodore	Roosevelt		),
    %w(	William	Taft	Howard	),
    %w(	Woodrow	Wilson		),
    %w(	Warren	Harding	G.	),
    %w(	Calvin	Coolidge		),
    %w(	Herbert	Hoover		),
    %w(	Franklin	Roosevelt	D.	),
    %w(	Harry	Truman	S	),
    %w(	Dwight	Eisenhower	D.	),
    %w(	John	Kennedy	F.	),
    %w(	Lyndon	Johnson	B.	),
    %w(	Richard	Nixon		),
    %w(	Gerald	Ford		),
    %w(	Jimmy	Carter		),
    %w(	Ronald	Reagan		),
    %w(	George	Bush		),
    %w(	Bill	Clinton		),
    %w(	George	Bush	W.	),
    %w(	Barack	Obama		)
]

presidents.each do |p|
  President.find_or_create_by!(first_name: p[0], middle_name: p[2], last_name: p[1])
end

animals = %w(
  alligator
  alpaca
  ant
  antelope
  ape
  armadillo
  ass
  baboon
  badger
  bat
  bear
  beaver
  bee
  beetle
  buffalo
  burro
  butterfly
  camel
  caribou
  cat
  cattle
  cheetah
  chimpanzee
  chinchilla
  cicada
  clam
  cockroach
  cod
  coyote
  crab
  cricket
  crocodile
  crow
  deer
  dinosaur
  dog
  dolphin
  donkey
  duck
  eel
  elephant
  elk
  ferret
  fish
  fly
  fox
  frog
  gerbil
  giraffe
  gnat
  gnu
  goat
  goldfish
  gorilla
  grasshopper
  guinea\ pig
  hamster
  hare
  hedgehog
  herring
  hippopotamus
  hog
  hornet
  horse
  hound
  hyena
  impala
  insect
  jackal
  jellyfish
  kangaroo
  leopard
  lion
  lizard
  llama
  locust
  louse
  mallard
  mammoth
  manatee
  marten
  mink
  minnow
  mole
  monkey
  moose
  mosquito
  mouse
  mule
  muskrat
  otter
  ox
  oyster
  panda
  pig
  platypus
  porcupine
  porpoise
  prairie\ dog
  pug
  rabbit
  raccoon
  rat
  raven
  reindeer
  rhinoceros
  salmon
  sardine
  scorpion
  sea\ lion
  seal
  serval
  shark
  sheep
  skunk
  snail
  snake
  spider
  squirrel
  swine
  termite
  tiger
  toad
  tortoise
  trout
  turtle
  wallaby
  walrus
  wasp
  water\ buffalo
  weasel
  whale
  wildebeest
  wolf
  wombat
  woodchuck
  worm
  yak
  yellow\ jacket
  zebra
)

animals.each do |a|
  Animal.find_or_create_by!(name: a)
end

# overlap with state.capital
us_cities = [
    %w(	New\ York	NY	),
    %w(	Los\ Angeles	CA	),
    %w(	Chicago	IL	),
    %w(	Houston	TX	),
    %w(	Phoenix	AZ	),
    %w(	Philadelphia	PA	),
    %w(	San\ Antonio	TX	),
    %w(	Dallas	TX	),
    %w(	San\ Diego	CA	),
    %w(	San\ Jose	CA	),
    %w(	Detroit	MI	),
    %w(	San\ Francisco	CA	),
    %w(	Jacksonville	FL	),
    %w(	Indianapolis	IN	),
    %w(	Austin	TX	),
    %w(	Columbus	OH	),
    %w(	Fort\ Worth	TX	),
    %w(	Charlotte	NC	),
    %w(	Memphis	TN	),
    %w(	Baltimore	MD	),
    %w(	El\ Paso	TX	),
    %w(	Boston	MA	),
    %w(	Milwaukee	WI	),
    %w(	Denver	CO	),
    %w(	Seattle	WA	),
    %w(	Nashville	TN	),
    %w(	Washington	DC	),
    %w(	Las\ Vegas	NV	),
    %w(	Portland	OR	),
    %w(	Louisville	KY	),
    %w(	Oklahoma\ City	OK	),
    %w(	Tucson	AZ	),
    %w(	Atlanta	GA	),
    %w(	Albuquerque	NM	),
    %w(	Fresno	CA	),
    %w(	Sacramento	CA	),
    %w(	Long\ Beach	CA	),
    %w(	Mesa	AZ	),
    %w(	Kansas\ City	MO	),
    %w(	Omaha	NE	),
    %w(	Cleveland	OH	),
    %w(	Virginia\ Beach	VA	),
    %w(	Miami	FL	),
    %w(	Oakland	CA	),
    %w(	Raleigh	NC	),
    %w(	Tulsa	OK	),
    %w(	Minneapolis	MN	),
    %w(	Colorado\ Springs	CO	),
    %w(	Honolulu	HI	),
    %w(	Arlington	TX	),
    %w(	Wichita	KS	),
    %w(	St.\ Louis	MO	),
    %w(	Tampa	FL	),
    %w(	Santa\ Ana	CA	),
    %w(	Anaheim	CA	),
    %w(	Cincinnati	OH	),
    %w(	Bakersfield	CA	),
    %w(	Aurora	CO	),
    %w(	New\ Orleans	LA	),
    %w(	Pittsburgh	PA	),
    %w(	Riverside	CA	),
    %w(	Toledo	OH	),
    %w(	Stockton	CA	),
    %w(	Corpus\ Christi	TX	),
    %w(	Lexington	KY	),
    %w(	St.\ Paul	MN	),
    %w(	Anchorage	AK	),
    %w(	Newark	NJ	),
    %w(	Buffalo	NY	),
    %w(	Plano	TX	),
    %w(	Henderson	NV	),
    %w(	Lincoln	NE	),
    %w(	Fort\ Wayne	IN	),
    %w(	Glendale	AZ	),
    %w(	Greensboro	NC	),
    %w(	Chandler	AZ	),
    %w(	St.\ Petersburg	FL	),
    %w(	Jersey\ City	NJ	),
    %w(	Scottsdale	AZ	),
    %w(	Norfolk	VA	),
    %w(	Madison	WI	),
    %w(	Orlando	FL	),
    %w(	Birmingham	AL	),
    %w(	Baton\ Rouge	LA	),
    %w(	Durham	NC	),
    %w(	Laredo	TX	),
    %w(	Lubbock	TX	),
    %w(	Chesapeake	VA	),
    %w(	Chula\ Vista	CA	),
    %w(	Garland	TX	),
    %w(	Winston-Salem	NC	),
    %w(	North\ Las\ Vegas	NV	),
    %w(	Reno	NV	),
    %w(	Gilbert	AZ	),
    %w(	Hialeah	FL	),
    %w(	Arlington	VA	),
    %w(	Akron	OH	),
    %w(	Irvine	CA	),
    %w(	Rochester	NY	),
    %w(	Boise\ City	ID	),
    %w(	Modesto	CA	),
    %w(	Fremont	CA	),
    %w(	Montgomery	AL	),
    %w(	Spokane	WA	),
    %w(	Richmond	VA	),
    %w(	Yonkers	NY	),
    %w(	Irving	TX	),
    %w(	Shreveport	LA	),
    %w(	San\ Bernardino	CA	),
    %w(	Tacoma	WA	),
    %w(	Glendale	CA	),
    %w(	Des\ Moines	IA	),
    %w(	Augusta	GA	),
    %w(	Grand\ Rapids	MI	),
    %w(	Huntington\ Beach	CA	),
    %w(	Mobile	AL	),
    %w(	Moreno\ Valley	CA	),
    %w(	Little\ Rock	AR	),
    %w(	Amarillo	TX	),
    %w(	Columbus	GA	),
    %w(	Oxnard	CA	),
    %w(	Fontana	CA	),
    %w(	Knoxville	TN	),
    %w(	Fort\ Lauderdale	FL	),
    %w(	Salt\ Lake\ City	UT	),
    %w(	Newport\ News	VA	),
    %w(	Huntsville	AL	),
    %w(	Tempe	AZ	),
    %w(	Brownsville	TX	),
    %w(	Worcester	MA	),
    %w(	Fayetteville	NC	),
    %w(	Jackson	MS	),
    %w(	Tallahassee	FL	),
    %w(	Aurora	IL	),
    %w(	Ontario	CA	),
    %w(	Providence	RI	),
    %w(	Overland\ Park	KS	),
    %w(	Rancho\ Cucamonga	CA	),
    %w(	Chattanooga	TN	),
    %w(	Oceanside	CA	),
    %w(	Santa\ Clarita	CA	),
    %w(	Garden\ Grove	CA	),
    %w(	Vancouver	WA	),
    %w(	Grand\ Prairie	TX	),
    %w(	Peoria	AZ	),
    %w(	Rockford	IL	),
    %w(	Cape\ Coral	FL	),
    %w(	Springfield	MO	),
    %w(	Santa\ Rosa	CA	),
    %w(	Sioux\ Falls	SD	),
    %w(	Port\ St.\ Lucie	FL	),
    %w(	Dayton	OH	),
    %w(	Salem	OR	),
    %w(	Pomona	CA	),
    %w(	Springfield	MA	),
    %w(	Eugene	OR	),
    %w(	Corona	CA	),
    %w(	Pasadena	TX	),
    %w(	Joliet	IL	),
    %w(	Pembroke\ Pines	FL	),
    %w(	Paterson	NJ	),
    %w(	Hampton	VA	),
    %w(	Lancaster	CA	),
    %w(	Alexandria	VA	),
    %w(	Salinas	CA	),
    %w(	Palmdale	CA	),
    %w(	Naperville	IL	),
    %w(	Pasadena	CA	),
    %w(	Kansas\ City	KS	),
    %w(	Hayward	CA	),
    %w(	Hollywood	FL	),
    %w(	Lakewood	CO	),
    %w(	Torrance	CA	),
    %w(	Syracuse	NY	),
    %w(	Escondido	CA	),
    %w(	Fort\ Collins	CO	),
    %w(	Bridgeport	CT	),
    %w(	Orange	CA	),
    %w(	Warren	MI	),
    %w(	Elk\ Grove	CA	),
    %w(	Savannah	GA	),
    %w(	Mesquite	TX	),
    %w(	Sunnyvale	CA	),
    %w(	Fullerton	CA	),
    %w(	McAllen	TX	),
    %w(	Cary	NC	),
    %w(	Cedar\ Rapids	IA	),
    %w(	Sterling\ Heights	MI	),
    %w(	Columbia	SC	),
    %w(	Coral\ Springs	FL	),
    %w(	Carrollton	TX	),
    %w(	Elizabeth	NJ	),
    %w(	Hartford	CT	),
    %w(	Waco	TX	),
    %w(	Bellevue	WA	),
    %w(	New\ Haven	CT	),
    %w(	West\ Valley\ City	UT	),
    %w(	Topeka	KS	),
    %w(	Thousand\ Oaks	CA	),
    %w(	El\ Monte	CA	),
    %w(	McKinney	TX	),
    %w(	Concord	CA	),
    %w(	Visalia	CA	),
    %w(	Simi\ Valley	CA	),
    %w(	Olathe	KS	),
    %w(	Clarksville	TN	),
    %w(	Denton	TX	),
    %w(	Stamford	CT	),
    %w(	Provo	UT	),
    %w(	Springfield	IL	),
    %w(	Killeen	TX	),
    %w(	Abilene	TX	),
    %w(	Evansville	IN	),
    %w(	Gainesville	FL	),
    %w(	Vallejo	CA	),
    %w(	Ann\ Arbor	MI	),
    %w(	Peoria	IL	),
    %w(	Lansing	MI	),
    %w(	Lafayette	LA	),
    %w(	Thornton	CO	),
    %w(	Athens	GA	),
    %w(	Flint	MI	),
    %w(	Inglewood	CA	),
    %w(	Roseville	CA	),
    %w(	Charleston	SC	),
    %w(	Beaumont	TX	),
    %w(	Independence	MO	),
    %w(	Victorville	CA	),
    %w(	Santa\ Clara	CA	),
    %w(	Costa\ Mesa	CA	),
    %w(	Miami\ Gardens	FL	),
    %w(	Manchester	NH	),
    %w(	Miramar	FL	),
    %w(	Downey	CA	),
    %w(	Arvada	CO	),
    %w(	Allentown	PA	),
    %w(	Westminster	CO	),
    %w(	Waterbury	CT	),
    %w(	Norman	OK	),
    %w(	Midland	TX	),
    %w(	Elgin	IL	),
    %w(	West\ Covina	CA	),
    %w(	Clearwater	FL	),
    %w(	Cambridge	MA	),
    %w(	Pueblo	CO	),
    %w(	West\ Jordan	UT	),
    %w(	Round\ Rock	TX	),
    %w(	Billings	MT	),
    %w(	Erie	PA	),
    %w(	South\ Bend	IN	),
    %w(	Ventura	CA	),
    %w(	Fairfield	CA	),
    %w(	Lowell	MA	),
    %w(	Norwalk	CA	),
    %w(	Burbank	CA	),
    %w(	Richmond	CA	),
    %w(	Pompano\ Beach	FL	),
    %w(	High\ Point	NC	),
    %w(	Murfreesboro	TN	),
    %w(	Lewisville	TX	),
    %w(	Richardson	TX	),
    %w(	Daly\ City	CA	),
    %w(	Berkeley	CA	),
    %w(	Gresham	OR	),
    %w(	Wichita\ Falls	TX	),
    %w(	Green\ Bay	WI	),
    %w(	Davenport	IA	),
    %w(	Palm\ Bay	FL	),
    %w(	Columbia	MO	),
    %w(	Portsmouth	VA	),
    %w(	Rochester	MN	),
    %w(	Antioch	CA	),
    %w(	Wilmington	NC	),
    %w(	Centennial	CO	),
    %w(	Odessa	TX	),
    %w(	West\ Palm\ Beach	FL	),
    %w(	Rialto	CA	),
    %w(	Everett	WA	),
    %w(	Murrieta	CA	),
    %w(	Tyler	TX	),
    %w(	Temecula	CA	),
    %w(	Kenosha	WI	),
    %w(	Frisco	TX	),
    %w(	Sandy	UT	),
    %w(	South\ Gate	CA	),
    %w(	Carlsbad	CA	),
    %w(	Gary	IN	),
    %w(	Mission\ Viejo	CA	),
    %w(	North\ Charleston	SC	),
    %w(	Boulder	CO	),
    %w(	Compton	CA	),
    %w(	Hillsboro	OR	),
    %w(	Albany	NY	),
    %w(	Fargo	ND	),
    %w(	Lakeland	FL	),
    %w(	Orem	UT	),
    %w(	Brockton	MA	),
    %w(	Roanoke	VA	),
    %w(	Broken\ Arrow	OK	),
    %w(	Surprise	AZ	),
    %w(	Macon	GA	),
    %w(	El\ Cajon	CA	),
    %w(	Carson	CA	),
    %w(	Quincy	MA	),
    %w(	Clovis	CA	),
    %w(	San\ Mateo	CA	),
    %w(	Vacaville	CA	),
    %w(	San\ Angelo	TX	),
    %w(	Las\ Cruces	NM	),
    %w(	Beaverton	OR	),
    %w(	Greeley	CO	),
    %w(	New\ Bedford	MA	),
    %w(	Livonia	MI	),
    %w(	Vista	CA	),
    %w(	Fall\ River	MA	),
    %w(	Waukegan	IL	),
    %w(	Lawrence	KS	),
    %w(	Davie	FL	),
    %w(	Tuscaloosa	AL	),
    %w(	Redding	CA	),
    %w(	Lawton	OK	),
    %w(	Yuma	AZ	),
    %w(	Sunrise	FL	),
    %w(	Westminster	CA	),
    %w(	Sparks	NV	),
    %w(	Santa\ Monica	CA	),
    %w(	Roswell	GA	),
    %w(	Lynn	MA	),
    %w(	Nashua	NH	),
    %w(	Dearborn	MI	),
    %w(	Santa\ Maria	CA	),
    %w(	Spokane\ Valley	WA	),
    %w(	Santa\ Barbara	CA	),
    %w(	Alhambra	CA	),
    %w(	Longmont	CO	),
    %w(	Hesperia	CA	),
    %w(	Boca\ Raton	FL	),
    %w(	Fort\ Smith	AR	),
    %w(	Miami\ Beach	FL	),
    %w(	Warwick	RI	),
    %w(	Indio	CA	),
    %w(	Citrus\ Heights	CA	),
    %w(	Deltona	FL	),
    %w(	Federal\ Way	WA	),
    %w(	Hawthorne	CA	),
    %w(	Duluth	MN	),
    %w(	Lee's\ Summit	MO	),
    %w(	College\ Station	TX	),
    %w(	Yakima	WA	),
    %w(	Kent	WA	),
    %w(	Chico	CA	),
    %w(	Plantation	FL	),
    %w(	Norwalk	CT	),
    %w(	Chino	CA	),
    %w(	Pearland	TX	),
    %w(	Trenton	NJ	),
    %w(	Ogden	UT	),
    %w(	Sioux\ City	IA	),
    %w(	Sandy\ Springs	GA	),
    %w(	Suffolk	VA	),
    %w(	Whittier	CA	),
    %w(	Racine	WI	),
    %w(	Newton	MA	),
    %w(	Avondale	AZ	),
    %w(	Bloomington	MN	),
    %w(	Allen	TX	),
    %w(	Sugar\ Land	TX	),
    %w(	Reading	PA	),
    %w(	Cicero	IL	),
    %w(	Nampa	ID	),
    %w(	Troy	MI	),
    %w(	Livermore	CA	),
    %w(	Cranston	RI	),
    %w(	Newport\ Beach	CA	),
    %w(	Rio\ Rancho	NM	),
    %w(	Greenville	NC	),
    %w(	Edmond	OK	),
    %w(	Champaign	IL	),
    %w(	Camden	NJ	),
    %w(	Buena\ Park	CA	),
    %w(	Danbury	CT	),
    %w(	Tracy	CA	),
    %w(	San\ Marcos	CA	),
    %w(	Westland	MI	),
    %w(	Bellingham	WA	),
    %w(	Farmington\ Hills	MI	),
    %w(	Lakewood	CA	),
    %w(	Canton	OH	),
    %w(	Clifton	NJ	),
    %w(	Parma	OH	),
    %w(	San\ Leandro	CA	),
    %w(	Evanston	IL	),
    %w(	Baldwin\ Park	CA	),
    %w(	Melbourne	FL	),
    %w(	Longview	TX	),
    %w(	Bend	OR	),
    %w(	Merced	CA	),
    %w(	O'Fallon	MO	),
    %w(	Hammond	IN	),
    %w(	Decatur	IL	),
    %w(	Jacksonville	NC	),
    %w(	St.\ Joseph	MO	),
    %w(	Albany	GA	),
    %w(	Somerville	MA	),
    %w(	Lake\ Forest	CA	),
    %w(	Southfield	MI	),
    %w(	Missouri\ City	TX	),
    %w(	Deerfield\ Beach	FL	),
    %w(	Napa	CA	),
    %w(	Asheville	NC	),
    %w(	New\ Rochelle	NY	),
    %w(	Redwood\ City	CA	),
    %w(	Chino\ Hills	CA	),
    %w(	Arlington\ Heights	IL	),
    %w(	Fayetteville	AR	),
    %w(	Medford	OR	),
    %w(	Bellflower	CA	),
    %w(	Bloomington	IL	),
    %w(	Youngstown	OH	),
    %w(	Largo	FL	),
    %w(	St.\ George	UT	),
    %w(	Lynchburg	VA	),
    %w(	Wilmington	DE	),
    %w(	Gastonia	NC	),
    %w(	Bryan	TX	),
    %w(	Palm\ Coast	FL	),
    %w(	Bethlehem	PA	),
    %w(	Scranton	PA	),
    %w(	Kalamazoo	MI	),
    %w(	Union\ City	CA	),
    %w(	Upland	CA	),
    %w(	Santa\ Fe	NM	),
    %w(	Bloomington	IN	),
    %w(	Tustin	CA	),
    %w(	Pawtucket	RI	),
    %w(	Schaumburg	IL	),
    %w(	Edinburg	TX	),
    %w(	Plymouth	MN	),
    %w(	Mountain\ View	CA	),
    %w(	Brooklyn\ Park	MN	),
    %w(	League\ City	TX	),
    %w(	Lake\ Charles	LA	),
    %w(	Hoover	AL	),
    %w(	Hemet	CA	),
    %w(	Bolingbrook	IL	),
    %w(	Alameda	CA	),
    %w(	New\ Britain	CT	),
    %w(	Wyoming	MI	),
    %w(	Baytown	TX	),
    %w(	Appleton	WI	),
    %w(	Lorain	OH	),
    %w(	Apple\ Valley	CA	),
    %w(	Gulfport	MS	),
    %w(	Lynwood	CA	),
    %w(	Lawrence	MA	),
    %w(	Redlands	CA	),
    %w(	Flower\ Mound	TX	),
    %w(	Rochester\ Hills	MI	),
    %w(	Fishers	IN	),
    %w(	Mount\ Vernon	NY	),
    %w(	Turlock	CA	),
    %w(	Boynton\ Beach	FL	),
    %w(	Missoula	MT	),
    %w(	Springdale	AR	),
    %w(	Waukesha	WI	),
    %w(	Iowa\ City	IA	),
    %w(	Folsom	CA	),
    %w(	Marietta	GA	),
    %w(	Milpitas	CA	),
    %w(	Rock\ Hill	SC	),
    %w(	Mission	TX	),
    %w(	Palatine	IL	),
    %w(	Lauderhill	FL	),
    %w(	St.\ Cloud	MN	),
    %w(	Kenner	LA	),
    %w(	Meridian	ID	),
    %w(	Passaic	NJ	),
    %w(	Redondo\ Beach	CA	),
    %w(	Pleasanton	CA	),
    %w(	Carmel	IN	),
    %w(	Waterloo	IA	),
    %w(	Skokie	IL	),
    %w(	Dothan	AL	),
    %w(	Concord	NC	),
    %w(	Pontiac	MI	),
    %w(	Yorba\ Linda	CA	),
    %w(	Loveland	CO	),
    %w(	Layton	UT	),
    %w(	Rapid\ City	SD	),
    %w(	Mount\ Pleasant	SC	),
    %w(	Eau\ Claire	WI	),
    %w(	Fort\ Myers	FL	),
    %w(	East\ Orange	NJ	),
    %w(	Pharr	TX	),
    %w(	North\ Richland\ Hills	TX	),
    %w(	Manteca	CA	),
    %w(	Muncie	IN	),
    %w(	Harlingen	TX	),
    %w(	Laguna\ Niguel	CA	),
    %w(	St.\ Charles	MO	),
    %w(	Daytona\ Beach	FL	),
    %w(	Pittsburg	CA	),
    %w(	Delray\ Beach	FL	),
    %w(	Lafayette	IN	),
    %w(	Eagan	MN	),
    %w(	Jonesboro	AR	),
    %w(	Oshkosh	WI	),
    %w(	Weston	FL	),
    %w(	Walnut\ Creek	CA	),
    %w(	Camarillo	CA	),
    %w(	Kennewick	WA	),
    %w(	Jackson	TN	),
    %w(	Pico\ Rivera	CA	),
    %w(	Davis	CA	),
    %w(	Portland	ME	),
    %w(	Victoria	TX	),
    %w(	Janesville	WI	),
    %w(	South\ San\ Francisco	CA	),
    %w(	Hamilton	OH	),
    %w(	Bossier\ City	LA	),
    %w(	Cedar\ Park	TX	),
    %w(	Kissimmee	FL	),
    %w(	Springfield	OH	),
    %w(	Renton	WA	),
    %w(	Rancho\ Cordova	CA	),
    %w(	Union\ City	NJ	),
    %w(	Johnson\ City	TN	),
    %w(	Montebello	CA	),
    %w(	Coon\ Rapids	MN	),
    %w(	Maple\ Grove	MN	),
    %w(	San\ Clemente	CA	),
    %w(	Warner\ Robins	GA	),
    %w(	Lodi	CA	),
    %w(	Haverhill	MA	),
    %w(	Monterey\ Park	CA	),
    %w(	Yuba\ City	CA	),
    %w(	Eden\ Prairie	MN	),
    %w(	Schenectady	NY	),
    %w(	Shawnee	KS	),
    %w(	Bristol	CT	),
    %w(	Huntington\ Park	CA	),
    %w(	Rockville	MD	),
    %w(	Taylor	MI	),
    %w(	Bismarck	ND	),
    %w(	Encinitas	CA	),
    %w(	St.\ Clair\ Shores	MI	),
    %w(	Waltham	MA	),
    %w(	Flagstaff	AZ	),
    %w(	Revere	MA	),
    %w(	Terre\ Haute	IN	),
    %w(	Greenville	SC	),
    %w(	Temple	TX	),
    %w(	Council\ Bluffs	IA	),
    %w(	Goodyear	AZ	),
    %w(	Johns\ Creek	GA	),
    %w(	North\ Little\ Rock	AR	),
    %w(	West\ Allis	WI	),
    %w(	Palo\ Alto	CA	),
    %w(	Tamarac	FL	),
    %w(	Great\ Falls	MT	),
    %w(	Frederick	MD	),
    %w(	Tinley\ Park	IL	),
    %w(	Meriden	CT	),
    %w(	La\ Habra	CA	),
    %w(	Burnsville	MN	),
    %w(	Taylorsville	UT	),
    %w(	Vineland	NJ	),
    %w(	Gaithersburg	MD	),
    %w(	National\ City	CA	),
    %w(	Gardena	CA	),
    %w(	Franklin	TN	),
    %w(	Utica	NY	),
    %w(	Homestead	FL	),
    %w(	Conway	AR	),
    %w(	Bayonne	NJ	),
    %w(	White\ Plains	NY	),
    %w(	Anderson	IN	),
    %w(	Dubuque	IA	),
    %w(	Diamond\ Bar	CA	),
    %w(	Springfield	OR	),
    %w(	Royal\ Oak	MI	),
    %w(	Galveston	TX	),
    %w(	Des\ Plaines	IL	),
    %w(	Rocky\ Mount	NC	),
    %w(	Lakewood	WA	),
    %w(	Cheyenne	WY	),
    %w(	Rogers	AR	),
    %w(	Madera	CA	),
    %w(	Tulare	CA	),
    %w(	Lake\ Havasu\ City	AZ	),
    %w(	Ames	IA	),
    %w(	Midwest\ City	OK	),
    %w(	Arcadia	CA	),
    %w(	Woodbury	MN	),
    %w(	Santa\ Cruz	CA	),
    %w(	Auburn	AL	),
    %w(	Decatur	AL	),
    %w(	Port\ Arthur	TX	),
    %w(	North\ Miami	FL	),
    %w(	Rowlett	TX	),
    %w(	Taunton	MA	),
    %w(	Blue\ Springs	MO	),
    %w(	Perris	CA	),
    %w(	Saginaw	MI	),
    %w(	San\ Rafael	CA	),
    %w(	Malden	MA	),
    %w(	Medford	MA	),
    %w(	Fountain\ Valley	CA	),
    %w(	Owensboro	KY	),
    %w(	Orland\ Park	IL	),
    %w(	St.\ Peters	MO	),
    %w(	Conroe	TX	),
    %w(	Auburn	WA	),
    %w(	West\ Des\ Moines	IA	),
    %w(	Pasco	WA	),
    %w(	Paramount	CA	),
    %w(	Bowling\ Green	KY	),
    %w(	Blaine	MN	),
    %w(	Elyria	OH	),
    %w(	Chicopee	MA	),
    %w(	North\ Port	FL	),
    %w(	Pocatello	ID	),
    %w(	Carson\ City	NV	),
    %w(	Broomfield	CO	),
    %w(	Ocala	FL	),
    %w(	La\ Mesa	CA	),
    %w(	Petaluma	CA	),
    %w(	Lancaster	PA	),
    %w(	Port\ Orange	FL	),
    %w(	Woodland	CA	),
    %w(	Lakeville	MN	),
    %w(	Wellington	FL	),
    %w(	Wheaton	IL	),
    %w(	Rosemead	CA	),
    %w(	Idaho\ Falls	ID	),
    %w(	Milford	CT	),
    %w(	Margate	FL	),
    %w(	Novi	MI	),
    %w(	Casper	WY	),
    %w(	Hempstead	NY	),
    %w(	Santee	CA	),
    %w(	Pensacola	FL	),
    %w(	Kettering	OH	),
    %w(	Hoffman\ Estates	IL	),
    %w(	Cupertino	CA	),
    %w(	New\ Braunfels	TX	),
    %w(	Bradenton	FL	),
    %w(	Mount\ Prospect	IL	),
    %w(	Oak\ Lawn	IL	),
    %w(	Delano	CA	),
    %w(	San\ Marcos	TX	),
    %w(	Rocklin	CA	),
    %w(	Novato	CA	),
    %w(	Elkhart	IN	),
    %w(	Moore	OK	),
    %w(	Euless	TX	),
    %w(	Bowie	MD	),
    %w(	Chapel\ Hill	NC	),
    %w(	West\ Haven	CT	),
    %w(	Sarasota	FL	),
    %w(	Manhattan	KS	),
    %w(	Cathedral\ City	CA	),
    %w(	Normal	IL	),
    %w(	Battle\ Creek	MI	),
    %w(	Shoreline	WA	),
    %w(	Hattiesburg	MS	),
    %w(	Dearborn\ Heights	MI	),
    %w(	Porterville	CA	),
    %w(	Mentor	OH	),
    %w(	Middletown	OH	),
    %w(	Niagara\ Falls	NY	),
    %w(	Peabody	MA	),
    %w(	Cerritos	CA	),
    %w(	Grand\ Forks	ND	),
    %w(	Monroe	LA	),
    %w(	New\ Brunswick	NJ	),
    %w(	South\ Jordan	UT	),
    %w(	Corvallis	OR	),
    %w(	Highland	CA	),
    %w(	Cuyahoga\ Falls	OH	),
    %w(	Lake\ Elsinore	CA	),
    %w(	La\ Crosse	WI	),
    %w(	Palm\ Desert	CA	),
    %w(	Burlington	NC	),
    %w(	Lakewood	OH	),
    %w(	Sanford	FL	),
    %w(	Florissant	MO	),
    %w(	Colton	CA	),
    %w(	Grapevine	TX	),
    %w(	Watsonville	CA	),
    %w(	Coconut\ Creek	FL	),
    %w(	Pine\ Bluff	AR	),
    %w(	Charleston	WV	),
    %w(	Hanford	CA	),
    %w(	Minnetonka	MN	),
    %w(	Mishawaka	IN	),
    %w(	Apple\ Valley	MN	),
    %w(	Gilroy	CA	),
    %w(	Berwyn	IL	),
    %w(	Alpharetta	GA	),
    %w(	Smyrna	GA	),
    %w(	La\ Mirada	CA	),
    %w(	Joplin	MO	),
    %w(	Yucaipa	CA	),
    %w(	Bellevue	NE	),
    %w(	Placentia	CA	),
    %w(	Grand\ Junction	CO	),
    %w(	Georgetown	TX	),
    %w(	Rancho\ Santa\ Margarita	CA	),
    %w(	Mansfield	OH	),
    %w(	Oak\ Park	IL	),
    %w(	Redmond	WA	),
    %w(	Brentwood	CA	),
    %w(	Glendora	CA	),
    %w(	Downers\ Grove	IL	),
    %w(	Palm\ Beach\ Gardens	FL	),
    %w(	Huntington	WV	),
    %w(	San\ Ramon	CA	),
    %w(	Bedford	TX	),
    %w(	Jupiter	FL	),
    %w(	Poway	CA	),
    %w(	Perth\ Amboy	NJ	),
    %w(	Tigard	OR	),
    %w(	Logan	UT	),
    %w(	Alexandria	LA	),
    %w(	Valdosta	GA	),
    %w(	East\ Providence	RI	),
    %w(	Wilson	NC	),
    %w(	Albany	OR	),
    %w(	Middletown	CT	),
    %w(	Palm\ Springs	CA	),
    %w(	Sheboygan	WI	),
    %w(	Hendersonville	TN	),
    %w(	Greenwood	IN	),
    %w(	Stillwater	OK	),
    %w(	DeSoto	TX	),
    %w(	West\ Sacramento	CA	),
    %w(	Bartlett	TN	),
    %w(	Troy	NY	),
    %w(	Kentwood	MI	),
    %w(	Euclid	OH	),
    %w(	Enid	OK	),
    %w(	Kirkland	WA	),
    %w(	Buckeye	AZ	),
    %w(	Newark	OH	),
    %w(	Pinellas\ Park	FL	),
    %w(	Harrisburg	PA	),
    %w(	Cypress	CA	),
    %w(	Covina	CA	),
    %w(	Azusa	CA	),
    %w(	Lenexa	KS	),
    %w(	Lehi	UT	),
    %w(	Roseville	MI	),
    %w(	Salina	KS	),
    %w(	West\ New\ York	NJ	),
    %w(	Murray	UT	),
    %w(	Roswell	NM	),
    %w(	Barnstable\ Town	MA	),
    %w(	Glenview	IL	),
    %w(	Richland	WA	),
    %w(	Altoona	PA	),
    %w(	Mansfield	TX	),
    %w(	Portage	MI	),
    %w(	Plainfield	NJ	),
    %w(	Chesterfield	MO	),
    %w(	Elmhurst	IL	),
    %w(	East\ Lansing	MI	),
    %w(	Cleveland\ Heights	OH	),
    %w(	Grand\ Island	NE	),
    %w(	Kokomo	IN	),
    %w(	Biloxi	MS	),
    %w(	Edina	MN	),
    %w(	Maricopa	AZ	),
    %w(	DeKalb	IL	),
    %w(	St.\ Louis\ Park	MN	),
    %w(	Olympia	WA	),
    %w(	Summerville	SC	),
    %w(	Wauwatosa	WI	),
    %w(	Cedar\ Hill	TX	),
    %w(	Titusville	FL	),
    %w(	Binghamton	NY	),
    %w(	Bell\ Gardens	CA	),
    %w(	Danville	VA	),
    %w(	Texas\ City	TX	),
    %w(	Bountiful	UT	),
    %w(	Kingsport	TN	),
    %w(	Castle\ Rock	CO	),
    %w(	Dublin	CA	),
    %w(	Southaven	MS	),
    %w(	Methuen	MA	),
    %w(	Huntersville	NC	),
    %w(	Harrisonburg	VA	),
    %w(	Freeport	NY	),
    %w(	La\ Quinta	CA	),
    %w(	Warren	OH	),
    %w(	Parker	CO	),
    %w(	San\ Luis\ Obispo	CA	),
    %w(	Lincoln	CA	),
    %w(	Oro\ Valley	AZ	),
    %w(	East\ Point	GA	),
    %w(	Coeur\ d'Alene	ID	),
    %w(	Sierra\ Vista	AZ	),
    %w(	Woonsocket	RI	),
    %w(	Lawrence	IN	),
    %w(	Covington	KY	),
    %w(	Moline	IL	),
    %w(	Buffalo\ Grove	IL	),
    %w(	Lombard	IL	),
    %w(	Attleboro	MA	),
    %w(	Hackensack	NJ	),
    %w(	Coral\ Gables	FL	),
    %w(	Bonita\ Springs	FL	),
    %w(	Prescott	AZ	),
    %w(	Ceres	CA	),
    %w(	Pittsfield	MA	),
    %w(	Farmington	NM	),
    %w(	Strongsville	OH	),
    %w(	Kannapolis	NC	),
    %w(	Commerce\ City	CO	),
    %w(	Fairfield	OH	),
    %w(	Caldwell	ID	),
    %w(	Draper	UT	),
    %w(	Oakland\ Park	FL	),
    %w(	Ankeny	IA	),
    %w(	The\ Colony	TX	),
    %w(	Concord	NH	),
    %w(	Bartlett	IL	),
    %w(	Sayreville	NJ	),
    %w(	Twin\ Falls	ID	),
    %w(	Noblesville	IN	),
    %w(	Fond\ du\ Lac	WI	),
    %w(	Crystal\ Lake	IL	),
    %w(	Blacksburg	VA	),
    %w(	Newark	CA	),
    %w(	North\ Lauderdale	FL	),
    %w(	Chelsea	MA	),
    %w(	Aliso\ Viejo	CA	),
    %w(	Charlottesville	VA	),
    %w(	Hickory	NC	),
    %w(	Salem	MA	),
    %w(	Danville	CA	),
    %w(	Casa\ Grande	AZ	),
    %w(	Rancho\ Palos\ Verdes	CA	),
    %w(	Lompoc	CA	),
    %w(	Belleville	IL	),
    %w(	Leominster	MA	),
    %w(	Wilkes-Barre	PA	),
    %w(	Midland	MI	),
    %w(	Hutchinson	KS	),
    %w(	Fort\ Pierce	FL	),
    %w(	Bullhead\ City	AZ	),
    %w(	Littleton	CO	),
    %w(	Jefferson\ City	MO	),
    %w(	Lacey	WA	),
    %w(	La\ Puente	CA	),
    %w(	Westfield	MA	),
    %w(	Hoboken	NJ	),
    %w(	Rohnert\ Park	CA	),
    %w(	San\ Gabriel	CA	),
    %w(	San\ Bruno	CA	),
    %w(	Fitchburg	MA	),
    %w(	Haltom\ City	TX	),
    %w(	Sammamish	WA	),
    %w(	Edmonds	WA	),
    %w(	Muskogee	OK	),
    %w(	York	PA	),
    %w(	El\ Centro	CA	),
    %w(	Carol\ Stream	IL	),
    %w(	Columbus	IN	),
    %w(	Shelton	CT	),
    %w(	Quincy	IL	),
    %w(	Altamonte\ Springs	FL	),
    %w(	Holyoke	MA	),
    %w(	Beavercreek	OH	),
    %w(	Cleveland	TN	),
    %w(	Riverton	UT	),
    %w(	Hagerstown	MD	),
    %w(	Pflugerville	TX	),
    %w(	Urbana	IL	),
    %w(	Leesburg	VA	),
    %w(	Spartanburg	SC	),
    %w(	Hot\ Springs	AR	),
    %w(	Bozeman	MT	),
    %w(	State\ College	PA	),
    %w(	Atlantic\ City	NJ	),
    %w(	Muskegon	MI	),
    %w(	Coachella	CA	),
    %w(	Beverly	MA	),
    %w(	Collierville	TN	),
    %w(	Linden	NJ	),
    %w(	Coppell	TX	),
    %w(	Brookfield	WI	),
    %w(	Keller	TX	),
    %w(	Burlington	VT	),
    %w(	Madison	AL	),
    %w(	Hallandale\ Beach	FL	),
    %w(	New\ Berlin	WI	),
    %w(	Sumter	SC	),
    %w(	Campbell	CA	),
    %w(	Culver\ City	CA	),
    %w(	Hurst	TX	),
    %w(	Dublin	OH	),
    %w(	Prescott\ Valley	AZ	),
    %w(	Huntsville	TX	),
    %w(	Urbandale	IA	),
    %w(	Calexico	CA	),
    %w(	Temple\ City	CA	),
    %w(	Brea	CA	),
    %w(	Meridian	MS	),
    %w(	Rock\ Island	IL	),
    %w(	Morgan\ Hill	CA	),
    %w(	Sherman	TX	),
    %w(	Cedar\ Falls	IA	),
    %w(	Romeoville	IL	),
    %w(	North\ Miami\ Beach	FL	),
    %w(	Ormond\ Beach	FL	),
    %w(	Apopka	FL	),
    %w(	Marlborough	MA	),
    %w(	Goose\ Creek	SC	),
    %w(	Florence	AL	),
    %w(	Smyrna	TN	),
    %w(	Wylie	TX	),
    %w(	San\ Jacinto	CA	),
    %w(	Lima	OH	),
    %w(	Carpentersville	IL	),
    %w(	Pacifica	CA	),
    %w(	Monrovia	CA	),
    %w(	Goldsboro	NC	),
    %w(	Stanton	CA	),
    %w(	Wausau	WI	),
    %w(	Cape\ Girardeau	MO	),
    %w(	Everett	MA	),
    %w(	New\ Albany	IN	),
    %w(	Germantown	TN	),
    %w(	Huber\ Heights	OH	),
    %w(	Streamwood	IL	),
    %w(	Findlay	OH	),
    %w(	Portage	IN	),
    %w(	Lancaster	OH	),
    %w(	Park\ Ridge	IL	),
    %w(	Lake\ Oswego	OR	),
    %w(	Addison	IL	),
    %w(	Woburn	MA	),
    %w(	Gadsden	AL	),
    %w(	Calumet\ City	IL	),
    %w(	Hanover\ Park	IL	),
    %w(	Kearny	NJ	),
    %w(	Richmond	IN	),
    %w(	Del\ Rio	TX	),
    %w(	Bell	CA	),
    %w(	Panama\ City	FL	),
    %w(	Texarkana	TX	),
    %w(	Manhattan\ Beach	CA	),
    %w(	Chester	PA	),
    %w(	Longview	WA	),
    %w(	Montclair	CA	),
    %w(	Annapolis	MD	),
    %w(	Plainfield	IL	),
    %w(	Riviera\ Beach	FL	),
    %w(	Norwich	CT	),
    %w(	Moorpark	CA	),
    %w(	Puyallup	WA	),
    %w(	University\ City	MO	),
    %w(	Fort\ Lee	NJ	),
    %w(	Mankato	MN	),
    %w(	Tupelo	MS	),
    %w(	Westerville	OH	),
    %w(	Brentwood	TN	),
    %w(	Beloit	WI	),
    %w(	Duncanville	TX	),
    %w(	Dover	DE	),
    %w(	Maplewood	MN	),
    %w(	Greenfield	WI	),
    %w(	Wheeling	IL	),
    %w(	Rome	GA	),
    %w(	Moorhead	MN	),
    %w(	Valley\ Stream	NY	),
    %w(	Bremerton	WA	),
    %w(	West\ Hollywood	CA	),
    %w(	Dunedin	FL	),
    %w(	Bartlesville	OK	),
    %w(	Keizer	OR	),
    %w(	Marion	OH	),
    %w(	Greenville	MS	),
    %w(	Lancaster	TX	),
    %w(	Alamogordo	NM	),
    %w(	Dana\ Point	CA	),
    %w(	Long\ Beach	NY	),
    %w(	Roy	UT	),
    %w(	Gainesville	GA	),
    %w(	Bentonville	AR	),
    %w(	Lake\ Worth	FL	),
    %w(	Franklin	WI	),
    %w(	Claremont	CA	),
    %w(	Minot	ND	),
    %w(	Cottonwood\ Heights	UT	),
    %w(	Lincoln\ Park	MI	),
    %w(	Torrington	CT	),
    %w(	Rockwall	TX	),
    %w(	Manassas	VA	),
    %w(	Martinez	CA	),
    %w(	Fairbanks	AK	),
    %w(	Lewiston	ME	),
    %w(	San\ Dimas	CA	),
    %w(	Los\ Banos	CA	),
    %w(	Burleson	TX	),
    %w(	Hollister	CA	),
    %w(	San\ Juan\ Capistrano	CA	),
    %w(	Peachtree\ City	GA	),
    %w(	Leavenworth	KS	),
    %w(	Brunswick	OH	),
    %w(	Menomonee\ Falls	WI	),
    %w(	Lufkin	TX	),
    %w(	Marysville	WA	),
    %w(	Marana	AZ	),
    %w(	Beverly\ Hills	CA	),
    %w(	Columbia	TN	),
    %w(	La\ Porte	TX	),
    %w(	Wildwood	MO	),
    %w(	Woodridge	IL	),
    %w(	Holland	MI	),
    %w(	Friendswood	TX	),
    %w(	San\ Juan	TX	),
    %w(	Northbrook	IL	),
    %w(	Hilton\ Head\ Island	SC	),
    %w(	Stow	OH	),
    %w(	Gahanna	OH	),
    %w(	Bay\ City	MI	),
    %w(	Grove\ City	OH	),
    %w(	Pleasant\ Grove	UT	),
    %w(	Seaside	CA	),
    %w(	Delaware	OH	),
    %w(	Mundelein	IL	),
    %w(	Northglenn	CO	),
    %w(	Rome	NY	),
    %w(	Reynoldsburg	OH	),
    %w(	Dalton	GA	),
    %w(	La\ Verne	CA	),
    %w(	Cottage\ Grove	MN	),
    %w(	Rosenberg	TX	),
    %w(	East\ Palo\ Alto	CA	),
    %w(	Lynnwood	WA	),
    %w(	Jackson	MI	),
    %w(	Oak\ Creek	WI	),
    %w(	Twentynine\ Palms	CA	),
    %w(	Shakopee	MN	),
    %w(	Pekin	IL	),
    %w(	Inver\ Grove\ Heights	MN	),
    %w(	Weslaco	TX	),
    %w(	Winter\ Haven	FL	),
    %w(	Elk\ Grove\ Village	IL	),
    %w(	Grants\ Pass	OR	),
    %w(	Manitowoc	WI	),
    %w(	Apex	NC	),
    %w(	Merrillville	IN	),
    %w(	New\ Iberia	LA	),
    %w(	Petersburg	VA	),
    %w(	Richmond	KY	),
    %w(	Pleasant\ Hill	CA	),
    %w(	St.\ Charles	IL	),
    %w(	Marion	IA	),
    %w(	Roseville	MN	),
    %w(	Apache\ Junction	AZ	),
    %w(	Plant\ City	FL	),
    %w(	Richfield	MN	),
    %w(	Englewood	CO	),
    %w(	Winter\ Springs	FL	),
    %w(	Beaumont	CA	),
    %w(	Goshen	IN	),
    %w(	Long\ Branch	NJ	),
    %w(	Massillon	OH	),
    %w(	North\ Chicago	IL	),
    %w(	Oviedo	FL	),
    %w(	Bettendorf	IA	),
    %w(	Monroe	NC	),
    %w(	Houma	LA	),
    %w(	Eastpointe	MI	),
    %w(	Prattville	AL	),
    %w(	Michigan\ City	IN	),
    %w(	Fairborn	OH	),
    %w(	Watertown	MA	),
    %w(	Clovis	NM	),
    %w(	Bothell	WA	),
    %w(	Ocoee	FL	),
    %w(	Danville	IL	),
    %w(	Nacogdoches	TX	),
    %w(	Greenacres	FL	),
    %w(	Franklin	MA	),
    %w(	Butte-Silver\ Bow	MT	),
    %w(	Hopkinsville	KY	),
    %w(	Oakley	CA	),
    %w(	Socorro	TX	),
    %w(	Naugatuck	CT	),
    %w(	Upper\ Arlington	OH	),
    %w(	Glendale\ Heights	IL	),
    %w(	Norristown	PA	),
    %w(	Laguna\ Hills	CA	),
    %w(	Olive\ Branch	MS	),
    %w(	Lewiston	ID	),
    %w(	Bangor	ME	),
    %w(	Kennesaw	GA	),
    %w(	Parkersburg	WV	),
    %w(	Florence	SC	),
    %w(	Bethel\ Park	PA	),
    %w(	Spanish\ Fork	UT	),
    %w(	Mount\ Vernon	WA	),
    %w(	Oswego	IL	),
    %w(	Highland\ Park	IL	),
    %w(	Oregon\ City	OR	),
    %w(	Brighton	CO	),
    %w(	Jacksonville	AR	),
    %w(	Lawndale	CA	),
    %w(	Leawood	KS	),
    %w(	North\ Olmsted	OH	),
    %w(	Burien	WA	),
    %w(	North\ Tonawanda	NY	),
    %w(	McMinnville	OR	),
    %w(	Galesburg	IL	),
    %w(	Phenix\ City	AL	),
    %w(	Douglasville	GA	),
    %w(	Lauderdale\ Lakes	FL	),
    %w(	Juneau	AK	),
    %w(	Wheat\ Ridge	CO	),
    %w(	Vestavia\ Hills	AL	),
    %w(	Deer\ Park	TX	),
    %w(	Port\ Huron	MI	),
    %w(	West\ Lafayette	IN	),
    %w(	Walnut	CA	),
    %w(	San\ Pablo	CA	),
    %w(	Copperas\ Cove	TX	),
    %w(	Granite\ City	IL	),
    %w(	Schertz	TX	),
    %w(	Rochester	NH	),
    %w(	Walla\ Walla	WA	),
    %w(	Gurnee	IL	),
    %w(	Myrtle\ Beach	SC	),
    %w(	Chicago\ Heights	IL	),
    %w(	Liberty	MO	),
    %w(	Shawnee	OK	),
    %w(	Oak\ Park	MI	),
    %w(	Westlake	OH	),
    %w(	Fair\ Lawn	NJ	),
    %w(	Jeffersonville	IN	),
    %w(	Hobbs	NM	),
    %w(	Newnan	GA	),
    %w(	Saratoga	CA	),
    %w(	Andover	MN	),
    %w(	Valparaiso	IN	),
    %w(	Kearney	NE	),
    %w(	Algonquin	IL	),
    %w(	University\ Place	WA	),
    %w(	Royal\ Palm\ Beach	FL	),
    %w(	Gloucester	MA	),
    %w(	Marion	IN	),
    %w(	Hinesville	GA	),
    %w(	Tooele	UT	),
    %w(	Menlo\ Park	CA	),
    %w(	Texarkana	AR	),
    %w(	La\ Vergne	TN	),
    %w(	Ballwin	MO	),
    %w(	East\ Chicago	IN	),
    %w(	Wenatchee	WA	),
    %w(	West\ Bend	WI	),
    %w(	Cleburne	TX	),
    %w(	Newark	DE	),
    %w(	Burton	MI	),
    %w(	Ithaca	NY	),
    %w(	Lake\ in\ the\ Hills	IL	),
    %w(	Mason	OH	),
    %w(	Poughkeepsie	NY	),
    %w(	Morgantown	WV	),
    %w(	Bowling\ Green	OH	),
    %w(	Madison\ Heights	MI	),
    %w(	Jamestown	NY	),
    %w(	Williamsport	PA	),
    %w(	Benton	AR	),
    %w(	Westfield	NJ	),
    %w(	Aiken	SC	),
    %w(	Cooper\ City	FL	),
    %w(	Goleta	CA	),
    %w(	Alton	IL	),
    %w(	Winter\ Garden	FL	),
    %w(	Alabaster	AL	),
    %w(	Helena	MT	),
    %w(	Gallatin	TN	),
    %w(	North\ Royalton	OH	),
    %w(	Los\ Gatos	CA	),
    %w(	Sanford	NC	),
    %w(	Elmira	NY	),
    %w(	Lawrenceville	GA	),
    %w(	Aventura	FL	),
    %w(	Cookeville	TN	),
    %w(	Englewood	NJ	),
    %w(	Foster\ City	CA	),
    %w(	Cutler\ Bay	FL	),
    %w(	Salisbury	NC	),
    %w(	Garfield	NJ	),
    %w(	Millville	NJ	),
    %w(	Banning	CA	),
    %w(	Wheeling	WV	),
    %w(	Schererville	IN	),
    %w(	Saratoga\ Springs	NY	),
    %w(	East\ St.\ Louis	IL	),
    %w(	Des\ Moines	WA	),
    %w(	St.\ Cloud	FL	),
    %w(	Paso\ Robles	CA	),
    %w(	Waxahachie	TX	),
    %w(	Cedar\ City	UT	),
    %w(	Niles	IL	),
    %w(	Rahway	NJ	),
    %w(	Lindenhurst	NY	),
    %w(	Santa\ Paula	CA	),
    %w(	Dover	NH	),
    %w(	New\ Bern	NC	),
    %w(	Garden\ City	KS	),
    %w(	Adelanto	CA	),
    %w(	Bessemer	AL	),
    %w(	Springville	UT	),
    %w(	Atascadero	CA	),
    %w(	LaGrange	GA	),
    %w(	Northampton	MA	),
    %w(	Los\ Altos	CA	),
    %w(	Sun\ Prairie	WI	),
    %w(	Gladstone	MO	),
    %w(	Maywood	CA	),
    %w(	Salisbury	MD	),
    %w(	Raytown	MO	),
    %w(	Port\ Chester	NY	),
    %w(	North\ Ridgeville	OH	),
    %w(	Midvale	UT	),
    %w(	Soledad	CA	),
    %w(	Newburgh	NY	),
    %w(	Dania\ Beach	FL	),
    %w(	Agawam	MA	),
    %w(	Harvey	IL	),
    %w(	Rexburg	ID	),
    %w(	Kent	OH	),
    %w(	Henderson	KY	),
    %w(	Winter\ Park	FL	),
    %w(	Hilliard	OH	),
    %w(	Hobart	IN	),
    %w(	Round\ Lake\ Beach	IL	),
    %w(	Clearfield	UT	),
    %w(	Plainfield	IN	),
    %w(	Kingman	AZ	),
    %w(	Monterey	CA	),
    %w(	Florence	KY	),
    %w(	Oak\ Forest	IL	),
    %w(	Southgate	MI	),
    %w(	Garfield\ Heights	OH	),
    %w(	Burlingame	CA	),
    %w(	Savage	MN	),
    %w(	Oak\ Ridge	TN	),
    %w(	Laramie	WY	),
    %w(	Prichard	AL	),
    %w(	Monroeville	PA	),
    %w(	Morristown	TN	),
    %w(	Russellville	AR	),
    %w(	Burbank	IL	),
    %w(	O'Fallon	IL	),
    %w(	Batavia	IL	),
    %w(	Owasso	OK	),
    %w(	West\ Springfield	MA	),
    %w(	Lake\ Jackson	TX	),
    %w(	Brooklyn\ Center	MN	),
    %w(	Xenia	OH	),
    %w(	Mason\ City	IA	),
    %w(	Frankfort	KY	),
    %w(	Watertown	NY	),
    %w(	De\ Land	FL	),
    %w(	San\ Carlos	CA	),
    %w(	Slidell	LA	),
    %w(	Statesboro	GA	),
    %w(	Maryville	TN	),
    %w(	Glen\ Ellyn	IL	),
    %w(	Garner	NC	),
    %w(	Auburn	NY	),
    %w(	West\ Memphis	AR	),
    %w(	Wake\ Forest	NC	),
    %w(	American\ Fork	UT	),
    %w(	Oakdale	MN	),
    %w(	Anderson	SC	),
    %w(	Suisun\ City	CA	),
    %w(	College\ Park	MD	),
    %w(	Pullman	WA	),
    %w(	Matthews	NC	),
    %w(	Glen\ Cove	NY	),
    %w(	Gillette	WY	),
    %w(	McHenry	IL	),
    %w(	Opelika	AL	),
    %w(	Winona	MN	),
    %w(	Kirkwood	MO	),
    %w(	Garden\ City	MI	),
    %w(	Kankakee	IL	),
    %w(	Melrose	MA	),
    %w(	Weatherford	TX	),
    %w(	Mount\ Pleasant	MI	),
    %w(	Lansing	IL	),
    %w(	Eagle\ Pass	TX	),
    %w(	Harrison	NY	),
    %w(	Norco	CA	),
    %w(	Inkster	MI	),
    %w(	Southlake	TX	),
    %w(	Barberton	OH	),
    %w(	Mount\ Pleasant	WI	),
    %w(	Atwater	CA	),
    %w(	Imperial\ Beach	CA	),
    %w(	Thomasville	NC	),
    %w(	Tualatin	OR	),
    %w(	Paradise	CA	),
    %w(	Belvidere	IL	),
    %w(	Post\ Falls	ID	),
    %w(	Shaker\ Heights	OH	),
    %w(	Corsicana	TX	),
    %w(	Farmers\ Branch	TX	),
    %w(	West\ Chicago	IL	),
    %w(	Nicholasville	KY	),
    %w(	Wilmette	IL	),
    %w(	Statesville	NC	),
    %w(	Clinton	IA	),
    %w(	Seguin	TX	),
    %w(	Emporia	KS	),
    %w(	Clinton	MS	),
    %w(	Spring\ Valley	NY	),
    %w(	Carbondale	IL	),
    %w(	Spring\ Hill	TN	),
    %w(	Jeffersontown	KY	),
    %w(	Superior	WI	),
    %w(	Wooster	OH	),
    %w(	Plum	PA	),
    %w(	Benicia	CA	),
    %w(	Paramus	NJ	),
    %w(	Duluth	GA	),
    %w(	Homer\ Glen	IL	),
    %w(	Kyle	TX	),
    %w(	Easton	PA	),
    %w(	Paris	TX	),
    %w(	Trotwood	OH	),
    %w(	Allen\ Park	MI	),
    %w(	Medina	OH	),
    %w(	Collinsville	IL	),
    %w(	Maryland\ Heights	MO	),
    %w(	Winchester	VA	),
    %w(	New\ London	CT	),
    %w(	Fridley	MN	),
    %w(	Middletown	NY	),
    %w(	Marshalltown	IA	),
    %w(	SeaTac	WA	),
    %w(	Kaysville	UT	),
    %w(	Bristol	TN	),
    %w(	Dodge\ City	KS	),
    %w(	Sandusky	OH	),
    %w(	Holladay	UT	),
    %w(	Greenville	TX	),
    %w(	Ridgecrest	CA	),
    %w(	Carlsbad	NM	),
    %w(	Bergenfield	NJ	),
    %w(	Paducah	KY	),
    %w(	Salem	VA	),
    %w(	Sanger	CA	),
    %w(	Leander	TX	),
    %w(	Harker\ Heights	TX	),
    %w(	Hastings	NE	),
    %w(	Windsor	CA	),
    %w(	Enterprise	AL	),
    %w(	Hazelwood	MO	),
    %w(	Stevens\ Point	WI	),
    %w(	Riverside	OH	),
    %w(	Burlington	IA	),
    %w(	Eureka	CA	),
    %w(	West\ Linn	OR	),
    %w(	Fountain\ Hills	AZ	),
    %w(	Fremont	NE	),
    %w(	Fort\ Dodge	IA	),
    %w(	Zion	IL	),
    %w(	Corcoran	CA	),
    %w(	Zanesville	OH	),
    %w(	Shoreview	MN	),
    %w(	San\ Benito	TX	),
    %w(	Lafayette	CO	),
    %w(	Neenah	WI	),
    %w(	Maywood	IL	),
    %w(	Lafayette	CA	),
    %w(	Westmont	IL	),
    %w(	Vicksburg	MS	),
    %w(	Little\ Elm	TX	),
    %w(	San\ Luis	AZ	),
    %w(	Owatonna	MN	),
    %w(	University\ Park	TX	),
    %w(	Lockport	IL	),
    %w(	Ardmore	OK	),
    %w(	Paragould	AR	),
    %w(	De\ Pere	WI	),
    %w(	Belmont	CA	),
    %w(	Casselberry	FL	),
    %w(	El\ Mirage	AZ	),
    %w(	Rockledge	FL	),
    %w(	Bridgeton	NJ	),
    %w(	Wyandotte	MI	),
    %w(	Kingsville	TX	),
    %w(	Horn\ Lake	MS	),
    %w(	Lebanon	TN	),
    %w(	Wasco	CA	),
    %w(	Freeport	IL	),
    %w(	Asheboro	NC	),
    %w(	Barstow	CA	),
    %w(	Belton	MO	),
    %w(	Edwardsville	IL	),
    %w(	Greer	SC	),
    %w(	Redmond	OR	),
    %w(	Sherwood	AR	),
    %w(	Ponca\ City	OK	),
    %w(	East\ Cleveland	OH	),
    %w(	Desert\ Hot\ Springs	CA	),
    %w(	Cornelius	NC	),
    %w(	Hercules	CA	),
    %w(	Peekskill	NY	),
    %w(	Vernon\ Hills	IL	),
    %w(	Aberdeen	SD	),
    %w(	Loves\ Park	IL	),
    %w(	South\ Pasadena	CA	),
    %w(	Colleyville	TX	),
    %w(	Rockville\ Centre	NY	),
    %w(	Pearl	MS	),
    %w(	Crown\ Point	IN	),
    %w(	Queen\ Creek	AZ	),
    %w(	Ottumwa	IA	),
    %w(	Cudahy	CA	),
    %w(	Geneva	IL	),
    %w(	Big\ Spring	TX	),
    %w(	Caledonia	WI	),
    %w(	New\ Castle	PA	),
    %w(	Starkville	MS	),
    %w(	Mercer\ Island	WA	),
    %w(	Ridgewood	NJ	),
    %w(	Elizabethtown	KY	),
    %w(	New\ Lenox	IL	),
    %w(	Seal\ Beach	CA	),
    %w(	Chaska	MN	),
    %w(	North\ Platte	NE	),
    %w(	Lebanon	PA	),
    %w(	White\ Bear\ Lake	MN	),
    %w(	Lemon\ Grove	CA	),
    %w(	Issaquah	WA	),
    %w(	Elmwood\ Park	IL	),
    %w(	Grandview	MO	),
    %w(	Galt	CA	),
    %w(	Parkland	FL	),
    %w(	Watauga	TX	),
    %w(	Denison	TX	),
    %w(	Avon\ Lake	OH	),
    %w(	Laguna\ Beach	CA	),
    %w(	Doral	FL	),
    %w(	Staunton	VA	),
    %w(	Woodstock	IL	),
    %w(	Dolton	IL	),
    %w(	Lemoore	CA	),
    %w(	Fairfax	VA	),
    %w(	Homewood	AL	),
    %w(	Prior\ Lake	MN	),
    %w(	San\ Fernando	CA	),
    %w(	South\ Portland	ME	),
    %w(	Marshall	TX	),
    %w(	Ossining	NY	),
    %w(	Columbus	MS	),
    %w(	Lodi	NJ	),
    %w(	Wentzville	MO	),
    %w(	Papillion	NE	),
    %w(	Ramsey	MN	),
    %w(	Walker	MI	),
    %w(	Griffin	GA	),
    %w(	Athens	AL	),
    %w(	West\ Fargo	ND	),
    %w(	Maple\ Heights	OH	),
    %w(	Anniston	AL	),
    %w(	Cabot	AR	),
    %w(	Pascagoula	MS	),
    %w(	Mequon	WI	),
    %w(	Newport	RI	),
    %w(	Champlin	MN	),
    %w(	Chanhassen	MN	),
    %w(	Rolling\ Meadows	IL	),
    %w(	Reedley	CA	),
    %w(	Green	OH	),
    %w(	Tarpon\ Springs	FL	),
    %w(	Carteret	NJ	),
    %w(	Fitchburg	WI	),
    %w(	South\ Lake\ Tahoe	CA	),
    %w(	New\ Smyrna\ Beach	FL	),
    %w(	Norton\ Shores	MI	),
    %w(	Carrollton	GA	),
    %w(	Franklin	IN	),
    %w(	Muskego	WI	),
    %w(	Opelousas	LA	),
    %w(	Roselle	IL	),
    %w(	Elk\ River	MN	),
    %w(	Auburn	ME	),
    %w(	Hopewell	VA	),
    %w(	Woodstock	GA	),
    %w(	Lisle	IL	),
    %w(	Northport	AL	),
    %w(	Hudson	OH	),
    %w(	Romulus	MI	),
    %w(	Benbrook	TX	),
    %w(	Newberg	OR	),
    %w(	Norfolk	NE	),
    %w(	Watertown	WI	),
    %w(	Huntley	IL	),
    %w(	Sahuarita	AZ	),
    %w(	Centerville	OH	),
    %w(	Oxford	OH	),
    %w(	Cliffside\ Park	NJ	),
    %w(	Alvin	TX	),
    %w(	Yukon	OK	),
    %w(	Kerrville	TX	),
    %w(	Fredericksburg	VA	),
    %w(	Machesney\ Park	IL	),
    %w(	Selma	CA	),
    %w(	Austin	MN	),
    %w(	Moscow	ID	),
    %w(	East\ Peoria	IL	),
    %w(	Oak\ Harbor	WA	),
    %w(	Woodburn	OR	),
    %w(	Brawley	CA	),
    %w(	Canton	GA	),
    %w(	Palmetto\ Bay	FL	),
    %w(	Highland	IN	),
    %w(	Coronado	CA	),
    %w(	South\ Plainfield	NJ	),
    %w(	Temple\ Terrace	FL	),
    %w(	Duncan	OK	),
    %w(	Park\ Forest	IL	),
    %w(	Willoughby	OH	),
    %w(	Van\ Buren	AR	),
    %w(	Greenwood	SC	),
    %w(	Derby	KS	),
    %w(	Muscatine	IA	),
    %w(	Morton\ Grove	IL	),
    %w(	Alliance	OH	),
    %w(	Kingston	NY	),
    %w(	Keene	NH	),
    %w(	Kernersville	NC	),
    %w(	Darien	IL	),
    %w(	Key\ West	FL	),
    %w(	Kinston	NC	),
    %w(	Webster\ Groves	MO	),
    %w(	Laurel	MD	),
    %w(	Blue\ Island	IL	),
    %w(	Eagle\ Mountain	UT	),
    %w(	Searcy	AR	),
    %w(	Chillicothe	OH	),
    %w(	Agoura\ Hills	CA	),
    %w(	Garden\ City	NY	),
    %w(	El\ Cerrito	CA	),
    %w(	Villa\ Park	IL	),
    %w(	Syracuse	UT	),
    %w(	Calabasas	CA	),
    %w(	Brandon	MS	),
    %w(	McKeesport	PA	),
    %w(	Hastings	MN	),
    %w(	Leesburg	FL	),
    %w(	Munster	IN	),
    %w(	Athens	OH	),
    %w(	Del\ City	OK	),
    %w(	Herndon	VA	),
    %w(	Radcliff	KY	),
    %w(	Faribault	MN	),
    %w(	Lumberton	NC	),
    %w(	Troy	OH	),
    %w(	Mooresville	NC	),
    %w(	Waynesboro	VA	),
    %w(	Bainbridge\ Island	WA	),
    %w(	Clarksville	IN	),
    %w(	Solon	OH	),
    %w(	Melrose\ Park	IL	),
    %w(	Ashland	OH	),
    %w(	Bloomingdale	IL	),
    %w(	Libertyville	IL	),
    %w(	Duarte	CA	),
    %w(	Kiryas\ Joel	NY	),
    %w(	Mauldin	SC	),
    %w(	Havelock	NC	),
    %w(	Grayslake	IL	),
    %w(	Hazleton	PA	),
    %w(	Miami\ Lakes	FL	),
    %w(	Blythe	CA	),
    %w(	Forest\ Park	GA	),
    %w(	Mount\ Juliet	TN	),
    %w(	Charleston	IL	),
    %w(	Crystal	MN	),
    %w(	Independence	KY	),
    %w(	Jacksonville\ Beach	FL	),
    %w(	Johnstown	PA	),
    %w(	South\ Salt\ Lake	UT	),
    %w(	Loma\ Linda	CA	),
    %w(	Columbus	NE	),
    %w(	Georgetown	KY	),
    %w(	New\ Brighton	MN	),
    %w(	Naples	FL	),
    %w(	Ridgeland	MS	),
    %w(	Prairie\ Village	KS	),
    %w(	Port\ Hueneme	CA	),
    %w(	Ypsilanti	MI	),
    %w(	Shelby	NC	),
    %w(	Biddeford	ME	),
    %w(	Edgewater	FL	),
    %w(	South\ El\ Monte	CA	),
    %w(	Adrian	MI	),
    %w(	Ashland	OR	),
    %w(	Monroe	MI	),
    %w(	Ashland	KY	),
    %w(	Plainview	TX	),
    %w(	Pottstown	PA	),
    %w(	Pelham	AL	),
    %w(	South\ Euclid	OH	),
    %w(	Rosemount	MN	),
    %w(	Kalispell	MT	),
    %w(	La\ Porte	IN	),
    %w(	Sapulpa	OK	),
    %w(	Westfield	IN	),
    %w(	North\ Plainfield	NJ	),
    %w(	South\ Elgin	IL	),
    %w(	South\ Milwaukee	WI	),
    %w(	Ruston	LA	),
    %w(	Ferndale	MI	),
    %w(	Greenbelt	MD	),
    %w(	South\ Holland	IL	),
    %w(	Mountain\ Brook	AL	),
    %w(	Lake\ Forest	IL	),
    %w(	Sedalia	MO	),
    %w(	Forest\ Grove	OR	),
    %w(	Ferguson	MO	),
    %w(	Venice	FL	),
    %w(	Auburn\ Hills	MI	),
    %w(	Marquette	MI	),
    %w(	East\ Moline	IL	),
    %w(	Holly\ Springs	NC	),
    %w(	Millbrae	CA	),
    %w(	Florence	AZ	),
    %w(	Corinth	TX	),
    %w(	Mukilteo	WA	),
    %w(	North\ Augusta	SC	),
    %w(	Milwaukie	OR	),
    %w(	Milledgeville	GA	),
    %w(	Wadsworth	OH	),
    %w(	Gardner	MA	),
    %w(	Roseburg	OR	),
    %w(	Bixby	OK	),
    %w(	La\ Ca§ada\ Flintridge	CA	),
    %w(	Junction\ City	KS	),
    %w(	West\ Mifflin	PA	),
    %w(	Lockport	NY	),
    %w(	Oxford	AL	),
    %w(	Lake\ Zurich	IL	),
    %w(	Riverbank	CA	),
    %w(	Arnold	MO	),
    %w(	Roselle	NJ	),
    %w(	Piqua	OH	),
    %w(	Summit	NJ	),
    %w(	Lebanon	OH	),
    %w(	Hamtramck	MI	),
    %w(	Cumberland	MD	),
    %w(	Watertown	SD	),
    %w(	Crest\ Hill	IL	),
    %w(	Portsmouth	NH	),
    %w(	New\ Hope	MN	),
    %w(	Lexington	NC	),
    %w(	Yucca\ Valley	CA	),
    %w(	Kenmore	WA	),
    %w(	Mint\ Hill	NC	),
    %w(	Hays	KS	),
    %w(	Farragut	TN	),
    %w(	Golden\ Valley	MN	),
    %w(	Norwood	OH	),
    %w(	Dinuba	CA	),
    %w(	Easley	SC	),
    %w(	Oakdale	CA	),
    %w(	Portsmouth	OH	),
    %w(	Saginaw	TX	),
    %w(	Klamath\ Falls	OR	),
    %w(	Sebastian	FL	),
    %w(	Rock\ Springs	WY	),
    %w(	Lino\ Lakes	MN	),
    %w(	Lomita	CA	),
    %w(	Point\ Pleasant	NJ	),
    %w(	Bensenville	IL	),
    %w(	Snellville	GA	),
    %w(	Liberal	KS	),
    %w(	Elizabeth\ City	NC	),
    %w(	Balch\ Springs	TX	),
    %w(	Brownsburg	IN	),
    %w(	Gallup	NM	),
    %w(	College\ Park	GA	),
    %w(	Sidney	OH	),
    %w(	Maple\ Valley	WA	),
    %w(	Mountlake\ Terrace	WA	),
    %w(	El\ Dorado	AR	),
    %w(	Brookings	SD	),
    %w(	Clinton	UT	),
    %w(	Lynbrook	NY	),
    %w(	Pleasant\ Prairie	WI	),
    %w(	Hammond	LA	),
    %w(	Alice	TX	),
    %w(	Albertville	AL	),
    %w(	Miamisburg	OH	),
    %w(	McDonough	GA	),
    %w(	Parma\ Heights	OH	),
    %w(	Glassboro	NJ	),
    %w(	Macomb	IL	),
    %w(	Bethany	OK	),
    %w(	Tinton\ Falls	NJ	),
    %w(	Ashtabula	OH	),
    %w(	Fountain	CO	),
    %w(	Shelbyville	TN	),
    %w(	Deerfield	IL	),
    %w(	Pittsburg	KS	),
    %w(	East\ Ridge	TN	),
    %w(	Northfield	MN	),
    %w(	Hialeah\ Gardens	FL	),
    %w(	Germantown	WI	),
    %w(	Nogales	AZ	),
    %w(	Cary	IL	),
    %w(	South\ St.\ Paul	MN	),
    %w(	Stafford	TX	),
    %w(	Terrell	TX	),
    %w(	Eastlake	OH	),
    %w(	Ennis	TX	),
    %w(	Orange	TX	),
    %w(	Murrysville	PA	),
    %w(	Christiansburg	VA	),
    %w(	Acworth	GA	),
    %w(	Eagle	ID	),
    %w(	Sulphur	LA	),
    %w(	Crestview	FL	),
    %w(	Ottawa	IL	),
    %w(	Jacksonville	IL	),
    %w(	Plattsburgh	NY	),
    %w(	Palisades\ Park	NJ	),
    %w(	Evergreen\ Park	IL	),
    %w(	Hermosa\ Beach	CA	),
    %w(	Thomasville	GA	),
    %w(	Niles	OH	),
    %w(	Morristown	NJ	),
    %w(	Mokena	IL	),
    %w(	Seymour	IN	),
    %w(	Brook\ Park	OH	),
    %w(	Chowchilla	CA	),
    %w(	Sylvania	OH	),
    %w(	Brownwood	TX	),
    %w(	Louisville	CO	),
    %w(	Eustis	FL	),
    %w(	Mineola	NY	),
    %w(	Madisonville	KY	),
    %w(	Daphne	AL	),
    %w(	Farmington	MN	),
    %w(	Haines\ City	FL	),
    %w(	Wilsonville	OR	),
    %w(	Patterson	CA	),
    %w(	Warrensburg	MO	),
    %w(	Bourbonnais	IL	),
    %w(	Fairmont	WV	),
    %w(	Cartersville	GA	),
    %w(	Seminole	FL	),
    %w(	Decatur	GA	),
    %w(	Trussville	AL	),
    %w(	Port\ Angeles	WA	),
    %w(	Indian\ Trail	NC	),
    %w(	Coalinga	CA	),
    %w(	Bellwood	IL	),
    %w(	West\ St.\ Paul	MN	),
    %w(	Birmingham	MI	),
    %w(	Oregon	OH	),
    %w(	Altus	OK	),
    %w(	Rocky\ River	OH	),
    %w(	Fort\ Walton\ Beach	FL	),
    %w(	Pleasantville	NJ	),
    %w(	Selma	AL	),
    %w(	Evans	CO	),
    %w(	Nixa	MO	),
    %w(	Steubenville	OH	),
    %w(	Cudahy	WI	),
    %w(	Pinole	CA	),
    %w(	Moses\ Lake	WA	),
    %w(	Greenfield	IN	),
    %w(	Weirton	WV	),
    %w(	Brigham\ City	UT	),
    %w(	St.\ Matthews	KY	),
    %w(	Laurel	MS	),
    %w(	Alsip	IL	),
    %w(	Sachse	TX	),
    %w(	Central\ Falls	RI	),
    %w(	Logansport	IN	),
    %w(	Elmwood\ Park	NJ	),
    %w(	Pinecrest	FL	),
    %w(	Angleton	TX	),
    %w(	Tullahoma	TN	),
    %w(	Manchester	MO	),
    %w(	Baldwin	PA	),
    %w(	Shelbyville	IN	)
]

us_cities.each do |c|
  UsCity.find_or_create_by!(name: c[0], state: State.find_by(abbreviation: c[1]))
end
