# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

capitals_with_country = [
    %w(	Afghanistan 	Kabul	),
    %w(	Albania 	Tirana	),
    %w(	Algeria 	Algiers	),
    %w(	Andorra 	Andorra\ la\ Vella	),
    %w(	Angola 	Luanda	),
    %w(	Antigua\ and\ Barbuda 	Saint\ John's	),
    %w(	Argentina 	Buenos\ Aires	),
    %w(	Armenia 	Yerevan	),
    %w(	Australia 	Canberra	),
    %w(	Austria 	Vienna	),
    %w(	Azerbaijan 	Baku	),
    %w(	The\ Bahamas 	Nassau	),
    %w(	Bahrain 	Manama	),
    %w(	Bangladesh 	Dhaka	),
    %w(	Barbados 	Bridgetown	),
    %w(	Belarus 	Minsk	),
    %w(	Belgium 	Brussels	),
    %w(	Belize 	Belmopan	),
    %w(	Benin 	Porto\ Novo	),
    %w(	Bhutan 	Thimphu	),
    %w(	Bolivia 	La\ Paz	),
    %w(	Bolivia 	Sucre	),
    %w(	Bosnia\ and\ Herzegovina 	Sarajevo	),
    %w(	Botswana 	Gaborone	),
    %w(	Brazil 	Brasilia	),
    %w(	Brunei 	Bandar\ Seri\ Begawan	),
    %w(	Bulgaria 	Sofia	),
    %w(	Burkina\ Faso 	Ouagadougou	),
    %w(	Burundi 	Bujumbura	),
    %w(	Cambodia 	Phnom\ Penh	),
    %w(	Cameroon 	Yaounde	),
    %w(	Canada 	Ottawa	),
    %w(	Cape\ Verde 	Praia	),
    %w(	Central\ African\ Republic 	Bangui	),
    %w(	Chad 	N'Djamena	),
    %w(	Chile 	Santiago	),
    %w(	China 	Beijing	),
    %w(	Colombia 	Bogota	),
    %w(	Comoros 	Moroni	),
    %w(	Costa\ Rica 	San\ Jose	),
    %w(	Cote\ d'Ivoire 	Yamoussoukro	),
    %w(	Cote\ d'Ivoire 	Abidjan	),
    %w(	Croatia 	Zagreb	),
    %w(	Cuba 	Havana	),
    %w(	Cyprus 	Nicosia	),
    %w(	Czech\ Republic 	Prague	),
    %w(	Democratic\ Republic\ of\ the\ Congo 	Kinshasa	),
    %w(	Denmark 	Copenhagen	),
    %w(	Djibouti 	Djibouti	),
    %w(	Dominica 	Roseau	),
    %w(	Dominican\ Republic 	Santo\ Domingo	),
    %w(	East\ Timor 	Dili	),
    %w(	Ecuador 	Quito	),
    %w(	Egypt 	Cairo	),
    %w(	El\ Salvador 	San\ Salvador	),
    %w(	Equatorial\ Guinea 	Malabo	),
    %w(	Eritrea 	Asmara	),
    %w(	Estonia 	Tallinn	),
    %w(	Ethiopia 	Addis\ Ababa	),
    %w(	Federated\ States\ of\ Micronesia 	Palikir	),
    %w(	Fiji 	Suva	),
    %w(	Finland 	Helsinki	),
    %w(	France 	Paris	),
    %w(	Gabon 	Libreville	),
    %w(	The\ Gambia 	Banjul	),
    %w(	Georgia 	Tbilisi	),
    %w(	Germany 	Berlin	),
    %w(	Ghana 	Accra	),
    %w(	Greece 	Athens	),
    %w(	Grenada 	Saint\ George's	),
    %w(	Guatemala 	Guatemala\ City	),
    %w(	Guinea 	Conakry	),
    %w(	Guinea-Bissau	Bissau	),
    %w(	Guyana 	Georgetown	),
    %w(	Haiti 	Port-au-Prince	),
    %w(	Honduras 	Tegucigalpa	),
    %w(	Hungary 	Budapest	),
    %w(	Iceland 	Reykjavik	),
    %w(	India 	New\ Delhi	),
    %w(	Indonesia 	Jakarta	),
    %w(	Iran 	Tehran	),
    %w(	Iraq 	Baghdad	),
    %w(	Ireland 	Dublin	),
    %w(	Israel 	Jerusalem	),
    %w(	Italy 	Rome	),
    %w(	Jamaica 	Kingston	),
    %w(	Japan 	Tokyo	),
    %w(	Jordan 	Amman	),
    %w(	Kazakhstan 	Astana	),
    %w(	Kenya 	Nairobi	),
    %w(	Kiribati 	Tarawa	),
    %w(	Kosovo 	Pristina	),
    %w(	Kuwait 	Kuwait\ City	),
    %w(	Kyrgyzstan 	Bishkek	),
    %w(	Laos 	Vientiane	),
    %w(	Latvia 	Riga	),
    %w(	Lebanon 	Beirut	),
    %w(	Lesotho 	Maseru	),
    %w(	Liberia 	Monrovia	),
    %w(	Libya 	Tripoli	),
    %w(	Liechtenstein 	Vaduz	),
    %w(	Lithuania 	Vilnius	),
    %w(	Luxembourg 	Luxembourg	),
    %w(	Macedonia 	Skopje	),
    %w(	Madagascar 	Antananarivo	),
    %w(	Malawi 	Lilongwe	),
    %w(	Malaysia 	Kuala\ Lumpur	),
    %w(	Maldives 	Male	),
    %w(	Mali 	Bamako	),
    %w(	Malta 	Valletta	),
    %w(	Marshall\ Islands 	Majuro	),
    %w(	Mauritania 	Nouakchott	),
    %w(	Mauritius 	Port\ Louis	),
    %w(	Mexico 	Mexico\ City	),
    %w(	Moldova 	Chisinau	),
    %w(	Monaco 	Monaco	),
    %w(	Mongolia 	Ulaanbaatar	),
    %w(	Montenegro 	Podgorica	),
    %w(	Morocco 	Rabat	),
    %w(	Mozambique 	Maputo	),
    %w(	Myanmar 	Rangoon	),
    %w(	Myanmar 	Naypyidaw	),
    %w(	Namibia 	Windhoek	),
    %w(	Nauru 	Yaren	),
    %w(	Nepal 	Kathmandu	),
    %w(	Netherlands 	Amsterdam	),
    %w(	Netherlands 	The\ Hague	),
    %w(	New\ Zealand 	Wellington	),
    %w(	Nicaragua 	Managua	),
    %w(	Niger 	Niamey	),
    %w(	Nigeria 	Abuja	),
    %w(	North\ Korea 	Pyongyang	),
    %w(	Norway 	Oslo	),
    %w(	Oman 	Muscat	),
    %w(	Pakistan 	Islamabad	),
    %w(	Palau 	Melekeok	),
    %w(	Panama 	Panama\ City	),
    %w(	Papua\ New\ Guinea 	Port\ Moresby	),
    %w(	Paraguay 	Asuncion	),
    %w(	Peru 	Lima	),
    %w(	Philippines 	Manila	),
    %w(	Poland 	Warsaw	),
    %w(	Portugal 	Lisbon	),
    %w(	Qatar 	Doha	),
    %w(	Republic\ of\ the\ Congo 	Brazzaville	),
    %w(	Romania 	Bucharest	),
    %w(	Russia 	Moscow	),
    %w(	Rwanda 	Kigali	),
    %w(	Saint\ Kitts\ and\ Nevis 	Basseterre	),
    %w(	Saint\ Lucia 	Castries	),
    %w(	Saint\ Vincent\ and\ the\ Grenadines 	Kingstown	),
    %w(	Samoa 	Apia	),
    %w(	San\ Marino 	San\ Marino	),
    %w(	Sao\ Tome\ and\ Principe 	Sao\ Tome	),
    %w(	Saudi\ Arabia 	Riyadh	),
    %w(	Senegal 	Dakar	),
    %w(	Serbia 	Belgrade	),
    %w(	Seychelles 	Victoria	),
    %w(	Sierra\ Leone 	Freetown	),
    %w(	Singapore 	Singapore	),
    %w(	Slovakia 	Bratislava	),
    %w(	Slovenia 	Ljubljana	),
    %w(	Solomon\ Islands 	Honiara	),
    %w(	Somalia 	Mogadishu	),
    %w(	South\ Africa 	Pretoria	),
    %w(	South\ Africa 	Cape\ Town	),
    %w(	South\ Africa 	Bloemfontein	),
    %w(	South\ Korea 	Seoul	),
    %w(	South\ Sudan 	Juba	),
    %w(	South\ Sudan 	Ramciel	),
    %w(	Spain 	Madrid	),
    %w(	Sri\ Lanka 	Colombo	),
    %w(	Sri\ Lanka 	Sri\ Jayewardenepura\ Kotte	),
    %w(	Sudan 	Khartoum	),
    %w(	Suriname 	Paramaribo	),
    %w(	Swaziland 	Mbabane	),
    %w(	Sweden 	Stockholm	),
    %w(	Switzerland 	Bern	),
    %w(	Syria 	Damascus	),
    %w(	Taiwan 	Taipei	),
    %w(	Tajikistan 	Dushanbe	),
    %w(	Tanzania 	Dar\ es\ Salaam	),
    %w(	Tanzania 	Dodoma	),
    %w(	Thailand 	Bangkok	),
    %w(	Togo 	Lome	),
    %w(	Tonga 	Nuku'alofa	),
    %w(	Trinidad\ and\ Tobago 	Port-of-Spain	),
    %w(	Tunisia 	Tunis	),
    %w(	Turkey 	Ankara	),
    %w(	Turkmenistan 	Ashgabat	),
    %w(	Tuvalu 	Funafuti	),
    %w(	Uganda 	Kampala	),
    %w(	Ukraine 	Kiev	),
    %w(	United\ Arab\ Emirates 	Abu\ Dhabi	),
    %w(	United\ Kingdom 	London	),
    %w(	United\ States\ of\ America 	Washington\ D.C.	),
    %w(	Uruguay 	Montevideo	),
    %w(	Uzbekistan 	Tashkent	),
    %w(	Vanuatu 	Port-Vila	),
    %w(	Vatican\ City 	Vatican\ City	),
    %w(	Venezuela 	Caracas	),
    %w(	Vietnam 	Hanoi	),
    %w(	Yemen 	Sanaa	),
    %w(	Zambia 	Lusaka	),
    %w(	Zimbabwe 	Harare	)
]

capitals_with_country.each do |c|
  country = Country.find_or_create_by!(name: c[0])
  Capital.find_or_create_by!(name: c[1], country: country)
end

states = [
    %w(	Alabama	Montgomery	),
    %w(	Alaska	Juneau	),
    %w(	Arizona	Phoenix	),
    %w(	Arkansas	Little\ Rock	),
    %w(	California	Sacramento	),
    %w(	Colorado	Denver	),
    %w(	Connecticut	Hartford	),
    %w(	Delaware	Dover	),
    %w(	Florida	Tallahassee	),
    %w(	Georgia	Atlanta	),
    %w(	Hawaii	Honolulu	),
    %w(	Idaho	Boise	),
    %w(	Illinois	Springfield	),
    %w(	Indiana	Indianapolis	),
    %w(	Iowa	Des\ Moines	),
    %w(	Kansas	Topeka	),
    %w(	Kentucky	Frankfort	),
    %w(	Louisiana	Baton\ Rouge	),
    %w(	Maine	Augusta	),
    %w(	Maryland	Annapolis	),
    %w(	Massachusetts	Boston	),
    %w(	Michigan	Lansing	),
    %w(	Minnesota	St.\ Paul	),
    %w(	Mississippi	Jackson	),
    %w(	Missouri	Jefferson\ City	),
    %w(	Montana	Helena	),
    %w(	Nebraska	Lincoln	),
    %w(	Nevada	Carson\ City	),
    %w(	New\ Hampshire	Concord	),
    %w(	New\ Jersey	Trenton	),
    %w(	New\ Mexico	Santa\ Fe	),
    %w(	New\ York	Albany	),
    %w(	North\ Carolina	Raleigh	),
    %w(	North\ Dakota	Bismarck	),
    %w(	Ohio	Columbus	),
    %w(	Oklahoma	Oklahoma\ City	),
    %w(	Oregon	Salem	),
    %w(	Pennsylvania	Harrisburg	),
    %w(	Rhode\ Island	Providence	),
    %w(	South\ Carolina	Columbia	),
    %w(	South\ Dakota	Pierre	),
    %w(	Tennessee	Nashville	),
    %w(	Texas	Austin	),
    %w(	Utah	Salt\ Lake\ City	),
    %w(	Vermont	Montpelier	),
    %w(	Virginia	Richmond	),
    %w(	Washington	Olympia	),
    %w(	West\ Virginia	Charleston	),
    %w(	Wisconsin	Madison	),
    %w(	Wyoming	Cheyenne	)
]

states.each do |s|
  State.find_or_create_by!(name: s[0], capital: s[1])
end
